---
name: check

on:
  workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21', '1.22', '1.23']
    steps:
      - name: Checkout Warewulf
        uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check Warewulf code with golang linter (golang ${{ matrix.go-version }})
        run: make lint

  vet:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21', '1.22', '1.23']
    steps:
      - name: Checkout Warewulf
        uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
        with:
          go-version: ${{ matrix.go-version }}
      - name: Vet Warewulf code (golang ${{ matrix.go-version }})
        run: make vet

  fmt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21', '1.22', '1.23']
    steps:
      - name: Checkout Warewulf
        uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check Warewulf code for formatting (golang ${{ matrix.go-version }})
        run: test "$(make -s fmt | wc -l)" == 0

  deadcode:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21', '1.22', '1.23']
    steps:
      - name: Checkout Warewulf
        uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check for dead Warewulf code (golang ${{ matrix.go-version }})
        run: make deadcode

  testsuite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21', '1.22', '1.23']
    steps:
      - name: Checkout Warewulf
        uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run the test suite (golang ${{ matrix.go-version }})
        run: make test

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21', '1.22', '1.23']
    steps:
      - name: Checkout Warewulf
        uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build Warewulf (golang ${{ matrix.go-version }})
        run: make all
